### ISSUE TITLE
Cannot install in the last version of Flarum

### ISSUE THREAD

**Issue by PeopleInside** [franzliedke/flarum-open-links-in-new-tab#1]
Hi, i cannot install this on the latest version of Flarum 0.1.0-beta.11

  [InvalidArgumentException]
  Could not find a version of package franzl/flarum-open-links-in-new-tab matching your minimum-s
  tability (beta). Require it with an explicit version constraint allowing its desired stability.

I need this as you removed the link on new tab on the last Flarum version.
Seems this extension has 0 release and cannot be installed from composer.

**Comment by phenomlab** [comment]
Same issue as @PeopleInside

**Comment by PeopleInside** [comment]
For now i resolved in this way:
- edited composer.json on line where you should have `"minimum-stability": "beta",` so replaced beta with dev and you will have **"minimum-stability": "dev"**
-run on SSH: **composer require franzl/flarum-open-links-in-new-tab:master**
- at the end run **php flarum cache:clear**
- enable the extension

**Comment by phenomlab** [comment]
Whilst this probably works well in terms of solving the short-term issue, it may have a negative impact with the remainder of the extensions in your install.

**Comment by Ralkage** [comment]
@PeopleInside please keep in mind that there is no stable version or even 1.0.0 released at this time, it is currently labeled as dev-master on Packagist for a reason so use it at your own discretion ;)

**Comment by franzliedke** [comment]
I just tagged a v0.1.0. Please let me know whether that works for you. :smile:

**Comment by PeopleInside** [comment]
Seems run just again the command for install work. I edited back beta in JSON

In the extension I see this: 
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/69831959-0a5dc580-122c-11ea-96f0-0a81df12df22.jpg)

Should work i think. Will close the issue waiting for @phenomlab feedback

**Comment by phenomlab** [comment]
Confirmed working on my install. Thanks @franzliedke

**Comment by PeopleInside** [comment]
Thank you ❤️
